### ISSUE TITLE
  // , How do I copy and paste text?

### ISSUE THREAD

**Issue by v6** [subliun/Antox#100] opened 2015-06-17 15:34 UTC
// , I am sending some of the Tox IDs that I have in another client to the installation of subliun's Antox on my phone. 

I would like to add those Tox IDs to my phone. 

However, I cannot copy them easily and securely.

**Comment by zetok** [comment] 2015-06-18 09:31
duplicate of #42

**Closed** 2015-08-18 12:48 UTC
Labels: enhancement

**Comment by v6** [comment] 2015-08-21 22:08
// , Is this a wontfix?

**Comment by 00firestar00** [comment] 2015-08-22 04:57
The easier copy-paste is fixed, There hasn't been any work on the "securely" portion of this ticket
