### ISSUE TITLE
Avatar thumbnail isn't updated after selecting picture

### ISSUE THREAD

**Issue by agilob** [subliun/Antox#176] opened 2015-10-08 20:03 UTC
^

**Comment by subliun** [comment] 2015-10-16 11:37
You mean for contacts?

**Comment by subliun** [comment] 2015-10-16 11:41
It updates instantly for me.

**Comment by agilob** [comment] 2015-10-16 13:10
1. select picture
2. open drawer
3. you see old picture

**Comment by subliun** [comment] 2015-10-21 12:41
what do you mean "select picture"? I assume you mean: open settings > select avatar > close settings > open drawer > you see old picture

That's what I tested and I can't reproduce it.

**Comment by agilob** [comment] 2015-10-23 12:09
You want a video?

**Comment by subliun** [comment] 2015-10-23 12:10
I would enjoy it. :)

**Comment by subliun** [comment] 2015-10-24 11:45
Confirmed.

**Comment by agilob** [comment] 2015-10-24 12:45
I wanted to record it now, but antox doesn't start at all after recent upgrade...

**Comment by subliun** [comment] 2015-10-24 12:48
A few people have said that. A log would be greatly appreciated.

**Comment by subliun** [comment] 2015-10-24 23:18
Tempted to close as wontfix after 3 hours of debugging.

**Comment by subliun** [comment] 2015-10-24 23:34
scratch that I'm an idiot. fixed.

**Closed** 2015-10-25 01:22 UTC
Labels: bug
