### ISSUE TITLE
Installation fails - Android 2.3.6

### ISSUE THREAD

**Issue by markus1540** [subliun/Antox#17] opened 2015-02-14 22:07 UTC
Reporting this for an anonymous user:
Installation of Antox 0.15.100 from FDroid fails in Android 2.3.6.
Logcat:
```
02-14 22:19:27.648 D/szipinf ( 1504): Initializing inflate state
02-14 22:19:28.023 D/dalvikvm( 1504): GC_FOR_MALLOC freed 922K, 40% free 7327K/12103K, external 2855K/3343K, paused 134ms
02-14 22:19:28.187 D/dalvikvm( 1504): GC_FOR_MALLOC freed 239K, 40% free 7302K/12103K, external 2677K/3343K, paused 95ms
02-14 22:19:28.421 W/PackageParser( 1504): Exception reading AndroidManifest.xml in /data/app/vmdl-202325236.tmp
02-14 22:19:28.421 W/PackageParser( 1504): java.lang.SecurityException: META-INF/TOXFOUND.SF has invalid digest for res/drawable-mdpi-v4/ic_action_camera.png in /data/app/vmdl-202325236.tmp
02-14 22:19:28.421 W/PackageParser( 1504): 	at java.util.jar.JarVerifier.invalidDigest(JarVerifier.java:130)
02-14 22:19:28.421 W/PackageParser( 1504): 	at java.util.jar.JarVerifier.verifyCertificate(JarVerifier.java:357)
02-14 22:19:28.421 W/PackageParser( 1504): 	at java.util.jar.JarVerifier.readCertificates(JarVerifier.java:265)
02-14 22:19:28.421 W/PackageParser( 1504): 	at java.util.jar.JarFile.getInputStream(JarFile.java:389)
02-14 22:19:28.421 W/PackageParser( 1504): 	at android.content.pm.PackageParser.loadCertificates(PackageParser.java:343)
02-14 22:19:28.421 W/PackageParser( 1504): 	at android.content.pm.PackageParser.collectCertificates(PackageParser.java:514)
02-14 22:19:28.421 W/PackageParser( 1504): 	at com.android.server.PackageManagerService.installPackageLI(PackageManagerService.java:6034)
02-14 22:19:28.421 W/PackageParser( 1504): 	at com.android.server.PackageManagerService.access$2200(PackageManagerService.java:142)
02-14 22:19:28.421 W/PackageParser( 1504): 	at com.android.server.PackageManagerService$5.run(PackageManagerService.java:4777)
02-14 22:19:28.421 W/PackageParser( 1504): 	at android.os.Handler.handleCallback(Handler.java:587)
02-14 22:19:28.421 W/PackageParser( 1504): 	at android.os.Handler.dispatchMessage(Handler.java:92)
02-14 22:19:28.421 W/PackageParser( 1504): 	at android.os.Looper.loop(Looper.java:130)
02-14 22:19:28.421 W/PackageParser( 1504): 	at android.os.HandlerThread.run(HandlerThread.java:60)
02-14 22:19:28.421 E/PackageParser( 1504): Package im.tox.antox has no certificates at entry AndroidManifest.xml; ignoring!
02-14 22:19:28.718 D/dalvikvm( 1504): GC_EXPLICIT freed 658K, 39% free 7492K/12103K, external 2677K/3343K, paused 116ms
```

**Comment by louipc** [comment] 2015-02-14 22:48
This is a duplicate of https://github.com/subliun/Antox/issues/8

**Closed** 2015-02-15 18:12 UTC
